# Generated by Django 5.1.7 on 2025-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euros'), ('GBP', 'Pounds'), ('USD', 'US Dollars')], default='EUR', max_length=3),
        ),
    ]
