# Generated by Django 5.1.7 on 2025-04-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Send', 'Send'), ('Receive', 'Receive')], default='Send', max_length=7),
        ),
    ]
